"""create cycle tables (periods, cycle_settings, bbt_readings)

Revision ID: 72116a250308
Revises: 138290df3740
Create Date: 2026-05-22 16:58:56.061971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72116a250308'
down_revision: Union[str, Sequence[str], None] = '138290df3740'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbt_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_c', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('measure_time', sa.Time(), nullable=True),
    sa.Column('method', sa.String(length=16), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IS NULL OR method IN ('oral','vaginal','axillary','wrist','other')", name='ck_bbt_method'),
    sa.CheckConstraint('temp_c BETWEEN 35.00 AND 38.00', name='ck_bbt_temp_range'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_bbt_user_date')
    )
    op.create_index(op.f('ix_bbt_readings_user_id'), 'bbt_readings', ['user_id'], unique=False)
    op.create_table('cycle_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('avg_cycle_length', sa.Integer(), nullable=False),
    sa.Column('avg_period_length', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('auto', 'manual')", name='ck_cycle_settings_mode'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_settings_user_id'), 'cycle_settings', ['user_id'], unique=True)
    op.create_table('periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_date', name='uq_periods_user_start')
    )
    op.create_index(op.f('ix_periods_start_date'), 'periods', ['start_date'], unique=False)
    op.create_index(op.f('ix_periods_user_id'), 'periods', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_periods_user_id'), table_name='periods')
    op.drop_index(op.f('ix_periods_start_date'), table_name='periods')
    op.drop_table('periods')
    op.drop_index(op.f('ix_cycle_settings_user_id'), table_name='cycle_settings')
    op.drop_table('cycle_settings')
    op.drop_index(op.f('ix_bbt_readings_user_id'), table_name='bbt_readings')
    op.drop_table('bbt_readings')
    # ### end Alembic commands ###
