"""create daily_entries and daily_tags tables

Revision ID: 275983833fab
Revises: 72116a250308
Create Date: 2026-05-22 18:14:55.890389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '275983833fab'
down_revision: Union[str, Sequence[str], None] = '72116a250308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_daily_entries_user_date')
    )
    op.create_index(op.f('ix_daily_entries_user_id'), 'daily_entries', ['user_id'], unique=False)
    op.create_table('daily_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('tag_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['daily_entries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'category', 'tag_key', name='uq_daily_tags_entry_category_key')
    )
    op.create_index(op.f('ix_daily_tags_entry_id'), 'daily_tags', ['entry_id'], unique=False)
    op.create_index('ix_daily_tags_tag_key', 'daily_tags', ['tag_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_daily_tags_tag_key', table_name='daily_tags')
    op.drop_index(op.f('ix_daily_tags_entry_id'), table_name='daily_tags')
    op.drop_table('daily_tags')
    op.drop_index(op.f('ix_daily_entries_user_id'), table_name='daily_entries')
    op.drop_table('daily_entries')
    # ### end Alembic commands ###
