"""create media table

Revision ID: fd65957cba72
Revises: 275983833fab
Create Date: 2026-05-22 18:49:32.993599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd65957cba72'
down_revision: Union[str, Sequence[str], None] = '275983833fab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('original_path', sa.String(length=255), nullable=False),
    sa.Column('thumb_path', sa.String(length=255), nullable=True),
    sa.Column('preview_path', sa.String(length=255), nullable=True),
    sa.Column('exif_taken_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('image', 'pdf')", name='ck_media_kind'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'sha256', name='uq_media_owner_sha256')
    )
    op.create_index(op.f('ix_media_owner_id'), 'media', ['owner_id'], unique=False)
    op.create_index(op.f('ix_media_sha256'), 'media', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_sha256'), table_name='media')
    op.drop_index(op.f('ix_media_owner_id'), table_name='media')
    op.drop_table('media')
    # ### end Alembic commands ###
