"""create diary tables

Revision ID: 53da39263bad
Revises: fd65957cba72
Create Date: 2026-05-22 22:04:04.778581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53da39263bad'
down_revision: Union[str, Sequence[str], None] = 'fd65957cba72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.String(length=16), server_default='shared', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("visibility IN ('private', 'shared')", name='ck_diary_visibility'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diary_entries_author_id'), 'diary_entries', ['author_id'], unique=False)
    op.create_index(op.f('ix_diary_entries_date'), 'diary_entries', ['date'], unique=False)
    op.create_table('diary_media',
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['diary_id'], ['diary_entries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diary_id', 'media_id', name='pk_diary_media')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diary_media')
    op.drop_index(op.f('ix_diary_entries_date'), table_name='diary_entries')
    op.drop_index(op.f('ix_diary_entries_author_id'), table_name='diary_entries')
    op.drop_table('diary_entries')
    # ### end Alembic commands ###
